# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bcgv <- function(individual, positions, locus_effects, n_gam, se_level, min_rep, max_rep, m, p) {
    .Call('Meiosis_bcgv', PACKAGE = 'Meiosis', individual, positions, locus_effects, n_gam, se_level, min_rep, max_rep, m, p)
}

to_matrix <- function(x) {
    .Call('Meiosis_to_matrix', PACKAGE = 'Meiosis', x)
}

#' Seed the random number generator.
#'
#' A Mersenne Twister pseudo-random generator of 32-bit numbers with a state size of
#' 10037 bits is used (\url{http://www.cplusplus.com/reference/random/mt19937/}).
#'
#' @param seed Integer (default = \code{NULL}). If \code{NULL}, a random seed is used.
#'
#' @return The used seed.
#'
#' @examples
#' seed_rng(123L)
#' the_seed <- seed_rng()
#'
#' @export
seed_rng <- function(seed = NULL) {
    .Call('Meiosis_seed_rng', PACKAGE = 'Meiosis', seed)
}

calc_Lstar <- function(L, m, p, epsilon) {
    .Call('Meiosis_calc_Lstar', PACKAGE = 'Meiosis', L, m, p, epsilon)
}

crossover <- function(L, m, p, obligate_chiasma, Lstar) {
    .Call('Meiosis_crossover', PACKAGE = 'Meiosis', L, m, p, obligate_chiasma, Lstar)
}

meiosis_geno_ <- function(patalle, matalle, pos, L, m, p, obligate_chiasma, Lstar) {
    .Call('Meiosis_meiosis_geno_', PACKAGE = 'Meiosis', patalle, matalle, pos, L, m, p, obligate_chiasma, Lstar)
}

meiosis_geno <- function(individual, positions, xodat_param) {
    .Call('Meiosis_meiosis_geno', PACKAGE = 'Meiosis', individual, positions, xodat_param)
}

meiosis_xodat_ <- function(patalle, patloc, matalle, matloc, L, m, p, obligate_chiasma, Lstar) {
    .Call('Meiosis_meiosis_xodat_', PACKAGE = 'Meiosis', patalle, patloc, matalle, matloc, L, m, p, obligate_chiasma, Lstar)
}

meiosis_xodat <- function(individual, xodat_param) {
    .Call('Meiosis_meiosis_xodat', PACKAGE = 'Meiosis', individual, xodat_param)
}

cross_geno <- function(father, mother, positions, xodat_param) {
    .Call('Meiosis_cross_geno', PACKAGE = 'Meiosis', father, mother, positions, xodat_param)
}

cross_xodat <- function(father, mother, xodat_param) {
    .Call('Meiosis_cross_xodat', PACKAGE = 'Meiosis', father, mother, xodat_param)
}

dh_geno <- function(individual, positions, xodat_param) {
    .Call('Meiosis_dh_geno', PACKAGE = 'Meiosis', individual, positions, xodat_param)
}

dh_xodat <- function(individual, xodat_param) {
    .Call('Meiosis_dh_xodat', PACKAGE = 'Meiosis', individual, xodat_param)
}

realized_ibd <- function(individual_1, individual_2) {
    .Call('Meiosis_realized_ibd', PACKAGE = 'Meiosis', individual_1, individual_2)
}

realized_f <- function(individual) {
    .Call('Meiosis_realized_f', PACKAGE = 'Meiosis', individual)
}

meiosis_xodat_test_R <- function(patalle, patloc, matalle, matloc, L, m, p, obligate_chiasma, Lstar) {
    .Call('Meiosis_meiosis_xodat_test_R', PACKAGE = 'Meiosis', patalle, patloc, matalle, matloc, L, m, p, obligate_chiasma, Lstar)
}

meiosis_xodat_test_R2 <- function(patalle, patloc, matalle, matloc, L, m, p, obligate_chiasma, Lstar) {
    .Call('Meiosis_meiosis_xodat_test_R2', PACKAGE = 'Meiosis', patalle, patloc, matalle, matloc, L, m, p, obligate_chiasma, Lstar)
}

find_lb <- function(x, val) {
    .Call('Meiosis_find_lb', PACKAGE = 'Meiosis', x, val)
}

find_bf <- function(x, val) {
    .Call('Meiosis_find_bf', PACKAGE = 'Meiosis', x, val)
}

