# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bcgv <- function(individual, positions, locus_effects, n_gam, se_level, min_rep, max_rep, m, p) {
    .Call('Meiosis_bcgv', PACKAGE = 'Meiosis', individual, positions, locus_effects, n_gam, se_level, min_rep, max_rep, m, p)
}

to_matrix <- function(x) {
    .Call('Meiosis_to_matrix', PACKAGE = 'Meiosis', x)
}

#' @rdname seed_rng
seed_rng <- function(seed = NULL) {
    .Call('Meiosis_seed_rng', PACKAGE = 'Meiosis', seed)
}

#' @rdname calc_Lstar
calc_Lstar <- function(L, m, p, epsilon = NULL) {
    .Call('Meiosis_calc_Lstar', PACKAGE = 'Meiosis', L, m, p, epsilon)
}

#' @rdname crossover
crossover <- function(L, m, p, obligate_chiasma, Lstar) {
    .Call('Meiosis_crossover', PACKAGE = 'Meiosis', L, m, p, obligate_chiasma, Lstar)
}

#' @rdname meiosis_geno
meiosis_geno <- function(individual, positions, xoparam) {
    .Call('Meiosis_meiosis_geno', PACKAGE = 'Meiosis', individual, positions, xoparam)
}

#' @rdname meiosis_xo
meiosis_xo <- function(individual, xoparam) {
    .Call('Meiosis_meiosis_xo', PACKAGE = 'Meiosis', individual, xoparam)
}

#' @rdname cross_geno
cross_geno <- function(father, mother, positions, xoparam) {
    .Call('Meiosis_cross_geno', PACKAGE = 'Meiosis', father, mother, positions, xoparam)
}

#' @rdname cross_xo
cross_xo <- function(father, mother, xoparam) {
    .Call('Meiosis_cross_xo', PACKAGE = 'Meiosis', father, mother, xoparam)
}

#' @rdname dh_geno
dh_geno <- function(individual, positions, xoparam) {
    .Call('Meiosis_dh_geno', PACKAGE = 'Meiosis', individual, positions, xoparam)
}

#' @rdname dh_xo
dh_xo <- function(individual, xoparam) {
    .Call('Meiosis_dh_xo', PACKAGE = 'Meiosis', individual, xoparam)
}

#' @rdname realized_coancestry
realized_coancestry <- function(individual_1, individual_2 = NULL) {
    .Call('Meiosis_realized_coancestry', PACKAGE = 'Meiosis', individual_1, individual_2)
}

meiosis_xodat_test_R <- function(patalle, patloc, matalle, matloc, L, m, p, obligate_chiasma, Lstar) {
    .Call('Meiosis_meiosis_xodat_test_R', PACKAGE = 'Meiosis', patalle, patloc, matalle, matloc, L, m, p, obligate_chiasma, Lstar)
}

meiosis_xodat_test_R2 <- function(patalle, patloc, matalle, matloc, L, m, p, obligate_chiasma, Lstar) {
    .Call('Meiosis_meiosis_xodat_test_R2', PACKAGE = 'Meiosis', patalle, patloc, matalle, matloc, L, m, p, obligate_chiasma, Lstar)
}

find_lb <- function(x, val) {
    .Call('Meiosis_find_lb', PACKAGE = 'Meiosis', x, val)
}

find_bf <- function(x, val) {
    .Call('Meiosis_find_bf', PACKAGE = 'Meiosis', x, val)
}

